name: Create Archive
on:
  push:
    tags:
      - '*'
      - '*/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'overlay.zip'
        directory: 'resourcepack/'
        path: '../'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "overlay.zip"
        token: ${{ secrets.GITHUB_TOKEN }}        