name: Create and Upload ZIP to Release
on:
  push:
    tags:
      - '*'
      - '*/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create ZIP file
        run: zip -r '&e&lBSG big items overlay.zip' ./resourcepack
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "&e&lBSG big items overlay.zip"
        token: ${{ secrets.GITHUB_TOKEN }}        